### ISSUE TITLE
lime_graphics_opengl_GL.context is null (demo_web)

### ISSUE THREAD

**Issue by varadig** [openfl/starling#13]
I cant run the demo, because of the following error:

Demo_Web.js:16767 Uncaught TypeError: Cannot read property 'enable' of null
Demo_Web.js:8214 Uncaught TypeError: Cannot read property 'stencilFunc' of null

<img src="https://s31.postimg.org/4url8ftdn/Screen_Shot_2016_07_31_at_16_50_57.png">

**Comment by vroad** [comment]
Which version of lime/openfl are you using?

**Comment by vroad** [comment]
Looks like a problem introduced in the latest git version of official OpenFL. Subsequent commits introduced many issues other than this, and I can't even create Context3D now because it throws an exception...

https://github.com/openfl/openfl/pull/1224

**Comment by jgranick** [comment]
Hey guys,

This is caused by changes to OpenFL to not modify the display list when using Stage3D, `-Ddom` mode on HTML5 is currently not working on 'develop'

Stay tuned, and please pardon the dust as we work out some changes to our Stage3D support. You can also use the 'master' branch or the last haxelib release in the meantime for something more stable

**Comment by jgranick** [comment]
This is working with the latest Lime, OpenFL and the "v1.8" branch :smile:
