### ISSUE TITLE
Can't seem to set the width and height to no scale

### ISSUE THREAD

**Issue by peteshand** [openfl/starling#21]
I'm using 
`<window width="0" height="0" fps="60" if="html5" />`
however the starling context still seems to scale to take up the whole window (with letter box on left and right)

**Comment by jgranick** [comment]
This is the expected behavior for OpenFL on HTML5. Our default template scales the DIV of the content to fit 100% of the window, whether you use a window width/height of 0 in your project file (which sends resize events and resizes the canvas) or you specify and exact width and height (which in the default template letterboxes and scales up the canvas)

Setting pixel dimensions for the "#openfl-content" DIV would force the behavior you want
