### ISSUE TITLE
Images are not shown on html5 targets when texture size is not squared

### ISSUE THREAD

**Issue by zack-z** [openfl/starling#26]
Test code:

var bmpData:BitmapData = Assets.getBitmapData("assets/image.png");
var bmp:Bitmap = new Bitmap(bmpData);
var img:Image = Image.fromBitmap(bmp);
addChild(img);

If image.png has width == 129 px and height == 128 px, then under html5 there will be error and image will not be rendered. Works fine under flash target.

If image.png has width = 129 px and height == 129 px, then works ok under html5 and flash.

After debugging it seems the error is related to generating mipmaps, is there a way to fix this issue still using mipmaps?

**Comment by peteshand** [comment]
Hey there

Yes the issue is indeed related to MipMaps.
For the time being you'll need to do something like:

var bmpData:BitmapData = Assets.getBitmapData("assets/image.png");
var bmp:Bitmap = new Bitmap(bmpData);
#if flash
var img:Image = Image.fromBitmap(bmp);generateMipMaps = false
#else
var img:Image = Image.fromBitmap(bmp, false);
#end
addChild(img);

**Comment by jgranick** [comment]
This appears to work fine, now, with the latest development builds of OpenFL :smile:
