### ISSUE TITLE
On native builds, stage shrinks towards a single point in the middle of the screen

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/starling#35]
Er, this is a weird one, so probably best to just show you. Here's a minimal example:

[shrinkingbug.zip](https://github.com/openfl/starling/files/644876/shrinkingbug.zip)

In this example, an image is attached to the stage. On flash and html 5, it looks like this:

![flash](https://cloud.githubusercontent.com/assets/2874150/21084141/a977a98c-bff6-11e6-9966-193b71101b19.png)

On windows and mac, it looks like this:

![windows](https://cloud.githubusercontent.com/assets/2874150/21084143/b197b3aa-bff6-11e6-87b1-4946cf7529de.gif)

I haven't been able to make native builds recently, so I don't know when this started!

¯\\_(ツ)_/¯

**Comment by jgranick** [comment]
Very strange, Neko doesn't do this, so it's specific to C++

**Comment by jgranick** [comment]
I found it is caused by this edit:

https://github.com/openfl/starling/commit/28837731cb17a6e9d9c40ba5e17f3070954aad10

On the C++ target, I believe that an `Array<Int>` is being silently cast to `Vector<Float>` somehow, resulting in rounding off that produces this affect. The dynamic targets (Flash, Neko, JavaScript) don't behave this way because the data types aren't strict the same way.

Digging for a solution in OpenFL, but rolling back is a temporary fix. If you use a current version of OpenFL, though, you'll need the patch that disables the "shared context" behavior in `starling.core.Starling` or you'll get a white screen :smile:

**Comment by jgranick** [comment]
I tried to find a solution, but something about the `new` constructor, I can't force a situation where the 3.2.1 compiler will throw an error if you try and pass an Int-based array to initialize a float array. For now, I'm disabling the feature, and this is fixed :smile:
