### ISSUE TITLE
Mac target movie vector not animating.

### ISSUE THREAD

**Issue by frankhdz** [openfl/starling#44]
On neko and HTML5 movie clip vectors work and are animated. The mac target only displays the first frame of the movieclip  but does not play the rest.

**Comment by jgranick** [comment]
What version of Haxe and HXCPP are you using? Thank you 😃

**Comment by frankhdz** [comment]
Haxe 3.4.0
hxcpp 3.7.2

I am seeing the same thing on iOS target as well.

**Comment by jgranick** [comment]
With the latest versions of each library (and Haxe 3.4.2) the MovieClip portion of the Starling sample works properly on macOS.

If you have problems with any other sample code, please let me know and we can look into it. Otherwise, perhaps this is an issue with Haxe 3.4.0 (which is not supported by OpenFL, 3.2.1 and 3.4.2 are) or perhaps some older library :smile:

Thank you :smile:
