### ISSUE TITLE
scale9Grid does not work as expected 

### ISSUE THREAD

**Issue by Stortof** [openfl/starling#75]
(Starling 2)

Here is an example:

```
var texture: Texture = Root.ASSETS.getTexture("some_texture");
var image:Image = new Image(texture);
image.scale9Grid = new Rectangle(430, 0, 2, 192);
```
Then, changing **width** or **height** of the image has no effect.

**Comment by numero15** [comment]
I used it recently, it worked well.
`img = new Image(Game.assets.getTexture("myTexture"));
img.scale9Grid  = new Rectangle(A,  B, C, D);
img .width = 6;
img .height = 6;`

And a picture showing what the values of the scale9Grid rectangle means

![scale9](https://user-images.githubusercontent.com/9897351/33089682-b213f090-cef1-11e7-8c84-421c97aaeb55.png)

**Comment by jgranick** [comment]
@numero15 Is that on Starling 1.8, or Starling 2? Thanks :smile:

**Comment by numero15** [comment]
It's on starling 2

**Comment by Stortof** [comment]
yes on Starling 2!

**Comment by numero15** [comment]
Even if the scale 9 textures are correctly displayed (for me), there is something wrong with their pivot point. If i want to change it, i have to do something like this 
`img.pivotY = A * (B/C);`

A is the value to where i want to move the pivot. For a regular image I would have done 
`img.pivotY = A;`

But for a scale9 I have to add the B/C part :
B is the height of the texture
C is the height of the image (which is superior to the height of the texture because of the "stretching" allowed by the scale9.

**Comment by jgranick** [comment]
Flash and native are consistent in the current dev version of Starling, so either it is working properly (it was fixed in recent updates to the library) or it is consistently wrong, so something minor is funny about the `Image` class.

If there does appear to be a problem between the AS3 and Haxe versions, please make a change to the Starling Demo in AS3, take a screenshot, then share the modifications so we can do the same in the Haxe version of the Demo and look into this deeper. Thanks :smile:
